Added A New Book - quantum (subject : Physics)
EbookFoundation/free-science-books pull request #69
Opened 2020-10-16 05:37 UTC by MachO7

## What does this PR do?
Add Resource-- Adds another book

## For resources
### Description 

### Why is this valuable (or not) -- A book on Quantum Mechanics, provides amazing chronological insights

### How do we know it's really free? -- It is absolutely free...I've used it myself.

### For book lists, is it a book? -It is a book in .PDF format.

### Checklist:
- [check ] Not a duplicate
- [check ] Included author(s) if appropriate
- [Check ] Lists are in alphabetical order
- [Check ] Needed indications added (PDF, access notes, under construction)

2020-10-17 16:09 UTC, eshellman requested changes
good list (except for one) but need to clean up the spaces to satisfy linter.

2020-10-17 16:09 UTC, eshellman commented on free-science-books.md
> +* [Quantum : Einstein,Bohr and the great debate about the nature of reality](https://www.pdfdrive.com/quantum-einstein-bohr-and-the-great-debate-about-the-nature-of-reality-e193612567.html) - Manjit
In general, we do not link to file sharing sites.

2020-10-18 16:10 UTC, MachO7 commented
Thank You,
So, I need to align the spaces and we'll be good?


On Sat, Oct 17, 2020 at 9:39 PM Eric Hellman <notifications@github.com>
wrote:

> *@eshellman* requested changes on this pull request.
>
> good list (except for one) but need to clean up the spaces to satisfy
> linter.
> ------------------------------
>
> In free-science-books.md
> <https://github.com/EbookFoundation/free-science-books/pull/69#discussion_r506957649>
> :
>
> >  * [Problems in Introductory Physics](http://www.lightandmatter.com/problems/problems.pdf) - B. Crowell and B. Shotwell (PDF)
> +
> +* [Quantum : Einstein,Bohr and the great debate about the nature of reality](https://www.pdfdrive.com/quantum-einstein-bohr-and-the-great-debate-about-the-nature-of-reality-e193612567.html) - Manjit Kumar (PDF)
>
> In general, we do not link to file sharing sites.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EbookFoundation/free-science-books/pull/69#pullrequestreview-510996190>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHH3ZA3GRPJPCSHCRH5RJPTSLG6UTANCNFSM4SS4AGHQ>
> .
>

2020-10-20 00:25 UTC, eshellman commented
right

2020-10-20 04:15 UTC, MachO7 commented
I have made the necessary changes. The Space issues are sorted, the link now directs to Mega instead of PDFDrive since you said that file sharing sites aren't appreciated... Thanks

2020-10-20 04:20 UTC, MachO7 commented
Hello Eric,
Thanks for helping me out,
I have made the necessary changes
I have also commented about the same
in the pull-request I had made on GitHub.
I hope my PR is accepted now.
Regards,
Ojas,


On Tue, Oct 20, 2020 at 5:56 AM Eric Hellman <notifications@github.com>
wrote:

> right
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EbookFoundation/free-science-books/pull/69#issuecomment-712514099>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHH3ZAYCKHACZFB7EUU6UATSLTKKFANCNFSM4SS4AGHQ>
> .
>

2020-10-20 12:24 UTC, eshellman commented
mega is a file sharing site

2020-10-20 12:24 UTC, closed without merging